// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"35all_tools/conf"
	"35all_tools/internal/data/local"
	"35all_tools/internal/handler"
	"35all_tools/internal/model"
	"35all_tools/internal/router"
	"35all_tools/internal/server"
	"35all_tools/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp(engine *gin.Engine, conf2 *conf.WebServerConfig) (model.ServerRepo, error) {
	jsonRepo := local.NewJsonRepository()
	jsonSerive := service.NewJsonService(jsonRepo)
	base := handler.NewBase()
	jsonHanler := handler.NewJsonHandler(jsonSerive, base)
	enDeRepo := local.NewEnDeRepository()
	enDeService := service.NewEnDeService(enDeRepo)
	enDeHandler := handler.NewEnDeHandler(enDeService)
	symmetryEnDeRepo := local.NewSymmetryEnDeRepository(enDeRepo)
	symmetryEnDeService := service.NewSymmetryEnDeService(symmetryEnDeRepo)
	symmetryEnDeHandler := handler.NewSymmetryEnDeHandler(symmetryEnDeService)
	comprehensiveRepo := local.NewComprehensiveRepository()
	comprehensiveService := service.NewComprehensiveService(comprehensiveRepo)
	comprehensiveHandler := handler.NewComprehensiveHandler(comprehensiveService)
	apiRouter := router.NewApiRouter(engine, jsonHanler, enDeHandler, symmetryEnDeHandler, comprehensiveHandler)
	serverRepo := server.NewServer(engine, apiRouter, conf2)
	return serverRepo, nil
}
