// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"35all_tools/conf"
	"35all_tools/internal/data/local"
	"35all_tools/internal/handlers"
	"35all_tools/internal/model"
	"35all_tools/internal/router"
	"35all_tools/internal/server"
	"35all_tools/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp(engine *gin.Engine, conf2 *conf.WebServerConfig) (model.ServerRepo, error) {
	jsonRepo := local.NewJsonRepository()
	jsonSerive := service.NewJsonService(jsonRepo)
	base := handlers.NewBase()
	jsonHanler := handlers.NewJsonHandler(jsonSerive, base)
	apiRouter := router.NewApiRouter(engine, jsonHanler)
	serverRepo := server.NewServer(engine, apiRouter, conf2)
	return serverRepo, nil
}
