// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"chip_database/conf"
	"chip_database/internal/kernel"
	"chip_database/internal/route"
	"chip_database/internal/server"
	"chip_database/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApp(eneing *gin.Engine, c *conf.WebServerConfig) (*kernal.Kernel, error) {
	infoService := service.NewInfoService()
	info := server.NewInfo(infoService)
	apiRouter := route.NewApiRouter(eneing, info)
	kernel := kernal.New(eneing, c, apiRouter)
	return kernel, nil
}
