package common

const (
	REGISTER_MEMORY_USER = "MEMORY_USER"
	REGISTER_MEMORY_ROOM = "MEMORY_ROOM"
	REGISTER_MEMORY_PMAP = "MEMORY_PMAP"

	REGISTER_FILE_USER = "FILE_USER"
	REGISTER_FILE_ROOM = "FILE_ROOM"
	REGISTER_FILE_PMAP = "FILE_PMAP"
)
