// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"20red_police/internal/data/memory"
	"20red_police/internal/server"
	"20red_police/internal/service"
)

// Injectors from wire.go:

// wire.go
func initApp() *server.Server {
	user := memory.NewUser()
	userService := service.NewUserService(user)
	player := memory.NewPlayer()
	playerService := service.NewPlayerService(player)
	serverServer := server.NewServer(userService, playerService)
	return serverServer
}
